### PR TITLE
Fix search by block hash

### LINKED ISSUE #1081: Search by block hash does not find the block
Take any block hash, e.g. `4usxPdL68XbQXBeZPGj56wH1FAqrXhuFygHTz27xodMU`, and try to search it on Explorer. Even though I can perfectly open the page https://explorer.near.org/blocks/4usxPdL68XbQXBeZPGj56wH1FAqrXhuFygHTz27xodMU, the search still says that there is nothing found.

@shelegdmitriy Could you take a quick look at it?

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Resolves #1081

### CODE REVIEW

File: backend/src/router/block/get-hash-by-id.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export const router = trpc.router<Context>().query("getHashById", {
     let selection = indexerDatabase
       .selectFrom("blocks")
       .select("block_hash as hash");
-    if (isNaN(parseInt(blockId))) {
```
Comment (shelegdmitriy) [inline backend/src/router/block/get-hash-by-id.ts:16]: If we take blockHash from issue (`4usxPdL68XbQXBeZPGj56wH1FAqrXhuFygHTz27xodMU`) and `console.log("4usxPdL68XbQXBeZPGj56wH1FAqrXhuFygHTz27xodMU")` we'll see output `4` and `isNaN(parseInt("4usxPdL68XbQXBeZPGj56wH1FAqrXhuFygHTz27xodMU"))` returns `false`. If we use `Number` instead of `parseInt` - works as expected.

Comment (frol) [reply backend/src/router/block/get-hash-by-id.ts:16]: This still looks incorrect to me. It is possible that block hash will only contain digits, so it will appear as a very big number. Let’s change this condition to just checking the length (if it is 43-44 characters long, search it as block hash, otherwise, check if it is a number and search as if it is block height, and otherwise skip search completely, as it does not make any sense to search lets say frol.near block)

File: backend/src/router/block/get-hash-by-id.ts [hunk 2]
```diff
@@ -13,10 +13,12 @@ export const router = trpc.router<Context>().query("getHashById", {
...
+    if ([43, 44].indexOf(blockId.length) >= 0) {
       selection = selection.where("block_hash", "=", blockId);
-    } else {
+    } else if (!isNaN(parseInt(blockId))) {
```
Comment (luixo) [inline backend/src/router/block/get-hash-by-id.ts:18]: This will search for block `1account.near`, and those accounts are valid.

Comment (shelegdmitriy) [reply backend/src/router/block/get-hash-by-id.ts:18]: What if we use `Number`? So the condition will be `if (!isNaN(Number(blockId)))`

Comment (luixo) [reply backend/src/router/block/get-hash-by-id.ts]: LGTM

**Review by luixo — APPROVED** [review]
