### PR TITLE
fix(frontend): Fix values on circulating supply chart

### LINKED ISSUE #750: Circulating and total supply is 1000 times more than it should be
https://explorer.near.org/stats

Total supply at the beginning was 1000M
But on the chart, it's 1000 000 M (1 000 000 000 000)

Checked the data in the DB, it's fine. So it should be an error on Explorer side.

BTW, it anyway has too many zeros, let's show it in millions
@shelegdmitriy @frol what do you think?

Found another issue: we should not show this chart on Testnet, please remove it there

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Resolves #750 

We will show this chart only for `mainnet`:

Снимок экрана 2021-09-29 в 13 52 46

### CODE REVIEW

File: frontend/src/components/stats/CirculatingSupplyStats.tsx [hunk 1]
```diff
@@ -24,10 +24,12 @@ const CirculatingSupplyStats = ({ chartStyle }: Props) => {
             circulatingTokensSupply: new BN(circulatingTokensSupply)
               .divn(10 ** 6)
               .divn(10 ** 6)
+              .divn(10 ** 3)
```
Comment (telezhnaya) [inline frontend/src/components/stats/CirculatingSupplyStats.tsx:27]: Why do we have `10^15` here?
It should be `10^24` to convert from yocto to NEAR

Comment (shelegdmitriy) [reply frontend/src/components/stats/CirculatingSupplyStats.tsx:27]: Because of this https://github.com/near/near-explorer/blob/master/backend/src/db-utils.js#L494-L506
```
SELECT
  DATE_TRUNC('day', TO_TIMESTAMP(DIV(computed_at_block_timestamp, 1000*1000*1000))) AS date,
  DIV(circulating_tokens_supply, 1000*1000*1000) AS circulating_tokens_supply,
  DIV(total_tokens_supply, 1000*1000*1000) as total_tokens_supply
FROM aggregated__circulating_supply
ORDER BY date
```

Comment (telezhnaya) [reply frontend/src/components/stats/CirculatingSupplyStats.tsx:27]: Why did we decide to divide tokens with `10^9` in the select statement?

Comment (shelegdmitriy) [reply frontend/src/components/stats/CirculatingSupplyStats.tsx:27]: I decide to do so because we do such convertations in other similar requests so from the component side we'll receive the same lenght of values

Comment (telezhnaya) [reply frontend/src/components/stats/CirculatingSupplyStats.tsx:27]: I guess you could be confused with division for timestamps, we usually convert nanos to seconds.
Let's choose one place where we convert yocto to NEAR. I saw such conversions on JS side, so it's better to remove division for tokens in SQL statement

Comment (shelegdmitriy) [reply frontend/src/components/stats/CirculatingSupplyStats.tsx]: Take a look ones again please 😀

File: frontend/src/components/stats/CirculatingSupplyStats.tsx [hunk 2]
```diff
@@ -22,12 +22,12 @@ const CirculatingSupplyStats = ({ chartStyle }: Props) => {
           ({ date, circulatingTokensSupply, totalTokensSupply }) => ({
             date,
             circulatingTokensSupply: new BN(circulatingTokensSupply)
-              .divn(10 ** 6)
-              .divn(10 ** 6)
+              .div(new BN((10 ** 20).toString()))
+              .div(new BN((10 ** 4).toString()))
```
Comment (frol) [inline frontend/src/components/stats/CirculatingSupplyStats.tsx:26]: Use `NEAR_NOMINATION` (it is BN number of 10**24): https://github.com/near/near-explorer/blob/master/frontend/src/components/nodes/NodesCard.tsx#L25

**Review by frol — CHANGES_REQUESTED** [review]

**Review by telezhnaya — APPROVED** [review]
I still want to show numbers in millions (divided by `1 000 000`), it will look simpler, but it could be done in another PR

Everything looks good here for me 👍

**Comment by shelegdmitriy** [comment]
> I still want to show numbers in millions (divided by `1 000 000`), it will look simpler, but it could be done in another PR
> 
> 
> 
> Everything looks good here for me 👍 

Great! Would you mind to create an issue about it and assign to me?

**Comment by telezhnaya** [comment]
I mentioned it here https://github.com/near/near-explorer/issues/750
Just don't close it after merging this PR
