### PR TITLE
fix(backend): Current week should not be counted for weekly Active Accounts

### LINKED ISSUE #614: Weekly active users current week is cut off
When looking at the chart of the weekly active users, the last data point only shows days in the current week vs showing actually last 7d (similar problem as with daily before).

Screen Shot 2021-04-27 at 4 12 56 AM

### PR DESCRIPTION
**Pull request by frol**
Resolves #614

### CODE REVIEW

File: backend/src/db-utils.js [hunk 1]
```diff
@@ -371,6 +371,7 @@ const queryActiveAccountsCountAggregatedByWeek = async () => {
       FROM transactions
       JOIN execution_outcomes ON execution_outcomes.receipt_id = transactions.converted_into_receipt_id
       WHERE execution_outcomes.status IN ('SUCCESS_VALUE', 'SUCCESS_RECEIPT_ID')
+      AND transactions.block_timestamp < ((CAST(EXTRACT(EPOCH FROM DATE_TRUNC('week', NOW())) AS bigint)) * 1000 * 1000 * 1000)
```
Comment (frol) [inline backend/src/db-utils.js:374]: This is the fix. The rest in this PR is just an alignment to use the same functions everywhere instead of my tricks with integer divisions

**Review by icerove — APPROVED** [review]
