### PR TITLE
fix(frontend): Display transaction fee tooltip when amount is larger than 0.00001 N

### LINKED ISSUE #383: Transaction fee popup should not be empty
https://explorer.near.org/transactions/7aZRyvfRnZzMQtxmxvMnTGmrdR44osAnRhady5ZE39EY

Hover over the transaction fee and observe that currently it is empty.

image

### PR DESCRIPTION
**Pull request by icerove**
fix #383 
also add mainnet script in the package.json in frontend

### CODE REVIEW

File: frontend/src/components/utils/Balance.jsx [hunk 1]
```diff
@@ -43,6 +43,7 @@ export const showInYocto = (amountStr) => {
   if (amount.lte(YOCTO_NEAR_THRESHOLD)) {
     return formatWithCommas(amountStr) + " yoctoⓃ";
   }
+  return formatWithCommas(amountStr) + " yoctoⓃ";
```
Comment (frol) [inline frontend/src/components/utils/Balance.jsx:46]: Why do we need the condition? It seems that the code is the same
